# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Frontend Test

on:
  push:
    branches: [ "main", "main-frontend" ]
  pull_request:
    branches: [ "main", "main-frontend" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Node.js Install Dependencies
      run: npm install
      working-directory: frontend-program

    - name: Node.js Build
      run: npm run build
      working-directory: frontend-program
